stages:
  - test
  - deploy_infrastructure

test_modelo_abacates:
  stage: test
  script:
    - echo "Probando la precisión del modelo YOLO de aguacates..."
    - echo "Pruebas pasadas exitosamente"

deploy_com_terraform:
  stage: deploy_infrastructure
  image: hashicorp/terraform:light
  script:
    - echo "Iniciando Terraform..."
    - terraform init 
    - terraform plan
    - terraform apply -auto-approve
    - echo "Verificando el recurso creado en la infraestructura:"
    - cat estado_servidor.txt