services:

  backend-v2:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: agrodata-api-v2
    env_file:
      - .env
      - .env.v2
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    external_links:
      - agrodata-db:db    # nombre del contenedor : alias dentro del compose

  frontend-v2:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: agrodata-web-v2
    env_file:
      - frontend/.env.local
    ports:
      - "5174:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host
    depends_on:
      - backend-v2